export interface UserInfor {
     CODE: string,
      USERNAME: string,
      NAME: string,
      EDIT_TIME: string,
      ADDRESS_DETAIL: string,
      COMMUNE_NAME: string,
      DISTRICT_NAME: string,
      PROVINCE_NAME: string,
      COMPANY_NAME: string,
      NATION_NAME: string,
      BIRTHDAY: string,
      EMAIL: string,
      PHONE: string,
      STAFF_POSITTION_NAME: string,
      USERTYPE_NAME: string,
      USERTYPE_CODE: string,
      DATE_JOINED: string,
  }